version: '3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: ssp_db
    environment:
      POSTGRES_USER: "scoutadmin"
      POSTGRES_PASSWORD: "DB4ScoutServiceProgram"
      POSTGRES_DB: "main"
    ports:
      - 5432:5432

  scout-proxy:
    image: traefik:v2.2
    #command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-fileprovider.yml:/etc/traefik/traefik-fileprovider.yml

  backend:
    image: node:lts
    user: "node"
    working_dir: /home/node/app
    environment:
      - DBCREDENTIALS=postgres://scoutadmin:DB4ScoutServiceProgram@ssp_db:5432/main
    volumes:
      - ./backend:/home/node/app
    ports:
       - 3030:3030
    command: "npm run start"

  frontend:
    image: nginx:latest
    container_name: aoa_nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 8070:80
    labels:
      - traefik.http.routers.FrontendRouter.rule=PathPrefix(`/`)
      - traefik.http.services.Frontendervice.loadbalancer.server.port=80
