http:
  routers:
    BackendRouter:
      entryPoints:
        - web
      rule: "PathPrefix(`/sapi/`) || PathPrefix(`/sws`)"
      service: BackendService
    StationaryRouter:
      entryPoints:
        - web
      rule: "PathPrefix(`/stationary/`)"
      service: StationaryService
    FrontendRouter:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: FrontendService

  services:
    BackendService:
      loadBalancer:
        servers:
          - url: "http://backend:3030"
    FrontendService:
      loadBalancer:
        servers:
          - url: "http://mobile:80"
    StationaryService:
      loadBalancer:
        servers:
          - url: "http://stationary:80"

