api:
  insecure: true

log:
 level: DEBUG

entryPoints:
  web:
   address: ":80"

providers:
  file:
    filename: /etc/traefik/traefik-fileprovider.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
