const additions                     = require('./additions/additions.service')
const baseItems                     = require('./base-items/base-items.service')
const baseItemsHaveAdditions        = require('./base-items-have-additions/base-items-have-additions.service')
const categories                    = require('./categories/categories.service')
const env                           = require('./env/env.service')
const flavours                      = require('./flavours/flavours.service') 
const items                         = require('./items/items.service')
const orderedItems                  = require('./ordered-items/ordered-items.service')
const orderedItemsHaveExtensions    = require('./ordered-items-have-additions/ordered-items-have-additions.service')
const sizes                         = require('./sizes/sizes.service')
const tables                        = require('./tables/tables.service')

module.exports = function (app) {
  app.configure(additions)
  app.configure(baseItems)
  app.configure(baseItemsHaveAdditions)
  app.configure(categories)
  app.configure(env)
  app.configure(flavours)
  app.configure(items)
  app.configure(orderedItems)
  app.configure(orderedItemsHaveExtensions)
  app.configure(sizes)
  app.configure(tables)
}